M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date jue 29 ene 2026 22:08:17
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-29T22:08:17-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C5.000
%
G90
G05
T1
X130.045Y-117.77
T2
X104.0Y-104.0
X104.0Y-146.0
X146.0Y-104.0
X146.0Y-146.0
T3
X125.0Y-125.0
M30
